group: travis_latest
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
    include:
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35,coverage
        - python: 3.6
          env: TOX_ENV=py36
install:
    - pip install codecov
script:
    - coverage run
notifications:
    email: false
